### ISSUE TITLE
[DOC] Insert a "Getting Started" section after "Basics" section

### ISSUE THREAD

**Issue by ncros3** [Luos-io/Documentation#108]
I think the section "Update Luos, Robus and board's firmware" needs to be placed in a "Getting Started" guide next to "Basics" section. We could place a "Hello World" example in the same section. 
For now, instructions to setup tools and environment are not easy to find for someone who hasn't installed them already.

**Comment by JeromeGalan** [comment]
Done since Luos release v2.0.0
