### ISSUE TITLE
[DOC] Revision table for compatibility

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Documentation#110]
**Insert the documentation link:**
https://docs.luos.io/

**Describe the issue or the suggestion:**
Find the good Example, Luos, and LuosHal revisions working together is not really obvious.

**How would you fix the issue / which content would you add or delete?**
We should make a table allowing users to check their revisions.

**Comment by Simonbdy** [comment]
@nicolas-rabault would a table with each version's compatibility of Example, Luos, and LuosHal work?
Something like this (values are arbitrary):
![image](https://user-images.githubusercontent.com/26368107/123229946-0f056100-d4d7-11eb-98e0-e2534b0d946b.png)

Yes means compatible together, No means not compatible together.

**Comment by nicolas-rabault** [comment]
Yes but the problem is that there is a different revision for each examples.
Perhaps we should put only Luos on the left with a list of Luos revisions and instead of putting `yes` or  `no` under the examples project or LuosHAL we write the corresponding revision number.

**Comment by JeromeGalan** [comment]
There are versioning in documentation.
We are making releases in Luos repository :  https://github.com/Luos-io/Luos/releases
