### ISSUE TITLE
[DOC] Provide information about feature's availability vs Luos version

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Documentation#140]
The documentation misses a very clear indication about the availability of a given feature for each version of Luos. For instance:

![image](https://user-images.githubusercontent.com/19606002/138072379-1c8ec5af-bbe3-44e4-adf2-b3a8e2138af2.png)
or
![image](https://user-images.githubusercontent.com/19606002/138072460-db68c2a6-eab8-4458-9aeb-55138feb3ea7.png)

**Comment by Salem-Luos** [comment]
In progress...

**Comment by Simonbdy** [comment]
The documentation now provides a menu for choosing the version: 

![image](https://user-images.githubusercontent.com/26368107/158624088-8749c9e2-4302-41c9-953e-4b9a9b9be818.png)

I close this issue.
