### ISSUE TITLE
[DOC] Improve Bootloader tutorial by providing textual command line instructions

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Documentation#142]
**Insert the documentation link:**
https://docs.luos.io/pages/tutorials/luos-tools/bootloader.html#step-5-detection

**Describe the issue or the suggestion:**
The tutorial sometimes misses a textual command line that can be copy-pasted. The instruction is provided in a screenshot or earlier, but it is inconvenient as it prevents the user from simply copy-pasting the instructions.

I found such content is missing in:
- step 5
- end of step 6

**How would you fix the issue / which content would you add or delete?**
...

**Comment by JeromeGalan** [comment]
Done in last version
