### ISSUE TITLE
[DOC] Some regular texts and headers are displayed very small

### ISSUE THREAD

**Issue by Simonbdy** [Luos-io/Documentation#164]
**Insert the documentation link:**
https://docs.luos.io/docs/tools/boot
There may be other occurrences in other docs' pages

**Describe the issue or the suggestion:**

The first sentence appears smaller than the rest of the text:
![image](https://user-images.githubusercontent.com/26368107/144061155-45b583d4-ba74-4603-a276-6717cc749ba8.png)

Example with a h4 header:
![image](https://user-images.githubusercontent.com/26368107/144061526-e014827f-bdcb-4454-a8c0-cc49ef5ee7d5.png)

**How would you fix the issue / which content would you add or delete?**
The text is smaller because it's not in HTML tags and takes my computer's default font size
The h4 header should be bigger

Thanks

**Comment by Salem-Luos** [comment]
@alexgeron-Luos 
What about this ?
