### ISSUE TITLE
[DOC] Detection command for Json Api has evolved

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/Documentation#171]
https://docs.luos.io/docs/api/api-json

To launch a detection to a Gate with JSON API:

- In previous versions,  you had  to send command 
        **{"detection": {}}\r**

- Now, there is an \n at the message ending, so it must be replaced by:  
        **{"detection": {}}\r\n**

**Comment by JeromeGalan** [comment]
We should also search if there are other occurences of this problem on other documentation pages (in luos doc, readme.md ...)

**Comment by Simonbdy** [comment]
we got back to the first version:

`{"detection": {}}\n`

I close this. Thanks @JeromeGalan
