### ISSUE TITLE
[DOC] Dark mode link and text issues

### ISSUE THREAD

**Issue by Simonbdy** [Luos-io/Documentation#338]
**Insert the documentation link:**
Every tutorials pages
https://www.luos.io/tutorials/get-started
https://www.luos.io/tutorials/bootloader/intro
...

**Describe the issue or the suggestion:**
**Intro pages :** 
1. Text/links in the following sections are in black:
- Pre-requisites
- Supported Hardware
- Summary
![image](https://user-images.githubusercontent.com/26368107/172377504-821a429a-a145-4aa6-81c1-b57515024130.png)
![image](https://user-images.githubusercontent.com/26368107/172377527-fcd2b85b-de04-44a3-9289-a2c43130802f.png)

2. Levels and time icons are in black
![image](https://user-images.githubusercontent.com/26368107/172377697-a8d74612-6cc3-44e6-821b-42a062483e4a.png)

**Other tuto pages:**
Text/links in "Related content" sections are in black
![image](https://user-images.githubusercontent.com/26368107/172377431-e4084caa-e808-4ab1-8b7b-7b5ff4caba8e.png)

**How would you fix the issue / which content would you add or delete?**
...

**Comment by JeromeGalan** [comment]
Done, good job 👍
