### ISSUE TITLE
[DOC] MAX_RTB_ENTRY vs MAX_SERVICES_NUMBER macro

### ISSUE THREAD

**Issue by K0rdan** [Luos-io/Documentation#392]
**Insert the documentation link:**
https://www.luos.io/docs/luos-technology/services/routing-table

**Describe the issue or the suggestion:**
Hi, I found an issue with the documentation of the routing table (https://www.luos.io/docs/luos-technology/services/routing-table). 

**How would you fix the issue / which content would you add or delete?**
The macro MAX_SERVICES_NUMBER is used in the docs, whereas it is the macro MAX_RTB_ENTRY that is used in the code.

**Comment by Simonbdy** [comment]
This issue will be addressed on the [turborepo](https://github.com/Luos-io/luos) when in production

**Comment by Simonbdy** [comment]
Duplicate in turborepo: https://github.com/Luos-io/luos/issues/92
