### ISSUE TITLE
[DOC] ASK_PUB_CMD deprecated?

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Documentation#396]
**Insert the documentation link:**
https://www.luos.io/docs/next/luos-technology/message/advanced-message#time-triggered-update-messages

**Describe the issue or the suggestion:**
`ASK_PUB_CMD` doesn't exist anymore.

**How would you fix the issue / which content would you add or delete?**
I assume it should be replaced with `GET_CMD`.

**Comment by Simonbdy** [comment]
This issue needs to be checked after the [turborepo's](https://github.com/Luos-io/luos) go-to-prod.
