### ISSUE TITLE
[DOC] Dead link in bootloader's doc

### ISSUE THREAD

**Issue by fleborne** [Luos-io/Documentation#417]
**Insert the documentation link:**
https://www.luos.io/docs/tools/boot#applications

**Describe the issue or the suggestion:**
The link `[the Luos engine's repository](https://github.com/Luos-io/luos_engine/tree/main/Examples/Projects)` in the infobox is dead.

**How would you fix the issue / which content would you add or delete?**
...

**Comment by lorenzi-nicolas** [comment]
PR awaiting validation by @K0rdan. Turborepo needed: https://github.com/Luos-io/luos/pull/34

**Comment by Simonbdy** [comment]
This issue must be checked one last time when the turborepo luos is in production, then closed.

**Comment by Simonbdy** [comment]
Duplicate in turborepo: https://github.com/Luos-io/luos/issues/94
