### ISSUE TITLE
[DOC] add a missing step for module update

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Documentation#72]
**Insert the documentation link:**
https://docs.luos.io/pages/prototyping_boards/electronic-use.html#update-luos-robus-and-boards-firmware

**Describe the issue or the suggestion:**
In this section there is no step to load a project before compiling.

**How would you fix the issue / which content would you add or delete?**
add a specific step describing it.

**Comment by Simonbdy** [comment]
Step 1 already explains how to open a project
