### ISSUE TITLE
[DOC] Update newsletter form at the bottom of docs

### ISSUE THREAD

**Issue by Simonbdy** [Luos-io/Documentation#77]
**Insert the documentation link:**
https://docs.luos.io/

**Describe the issue or the suggestion:**
Replace the code for the newsletter form subscription in file index.hbs

**How would you fix the issue / which content would you add or delete?**
`<iframe frameborder="0" style="height:500px;width:99%;border:none;" src='https://forms.luos.io/luosio/form/Newslettersubscription/formperma/u2X9b0H-X_1jJ3wkPRG-5-4-kSMfbQmDUK_223DqZBs'></iframe>
`

**Comment by aniketrb-github** [comment]
Hi @Simonbdy, I just inspected the current code on the [website here](https://docs.luos.io/).
from what I understand, here we need to replace the entire <div class="cust_nl"> . . . </div> tag with the above mentioned <iframe> tag. 
Please correct my understanding if it is incorrect. Thanks.

**Comment by Simonbdy** [comment]
Hi @aniketrb-github, you are correct, thank you very much. I'll do the modification later.
Cheers

**Comment by aniketrb-github** [comment]
> Hi @aniketrb-github, you are correct, thank you very much. I'll do the modification later.
> Cheers

Oh...I thought this was an issue which is which was more of like "up-for-grabs". Well. 
Okay, not a problem. Thanks for your response though.

**Comment by Simonbdy** [comment]
Resolved by 8daaf2694fee90eede838842b4eb59db71ccf67c
