### ISSUE TITLE
[DOC] Stepper modes are functions

### ISSUE THREAD

**Issue by ymollard** [Luos-io/Documentation#86]
**Insert the documentation link:**
https://github.com/Luos-io/Documentation/blame/master/src/pages/high/modules_list/stepper.md#L36-L39

**Describe the issue or the suggestion:**
The 4 modes are documented as variables, but in Pyluos 1.2.3 they're functions. 

**How would you fix the issue / which content would you add or delete?**
Either:
1. the doc is wrong and should list them as functions with their boolean parameter ; or
2. the doc is right and modes should be converted into variables in Pyluos 

Knowing that in all other modules it is frequent to activate something with variables e.g. `controlled_motor.rot_speed_mode = True`, the second option looks preferable to me.

**Comment by nicolas-rabault** [comment]
Indeed, it sounds like a mistake on the pyluos code side.
We have to update pyluos about it.

**Comment by Simonbdy** [comment]
@nicolas-rabault, is this issue still open?

**Comment by nicolas-rabault** [comment]
The stepper example is now a standard servomotor from Luos 1.3.0, so we have to remove the stepper page related to on pyluos and remove this from pyluos too. So this issue doesn't exist anymore but we still have another problem. We should close this one and open another.

**Comment by nicolas-rabault** [comment]
We have the same problem with dxl...

**Comment by JeromeGalan** [comment]
There is no more demo board on the documentation
